baseURL = "https://giovannimartins.dev/"
title = "Giovanni Martins"
theme = "keepitnew"
copyright = "2022 © Giovanni Martins"
enableEmoji = true
enableRobotsTXT = true
defaultContentLanguage = "en"
Paginate = 10
preserveTaxonomyNames = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 2

[params]
  author = "Giovanni Martins"
  subtitle = "Software Engineer @ Conviso Application Security"
  subtitle_additional = "Ruby, Typescript, AppSec, Docker, Dapr and more..."
  subtitle_additional_2 = "de omnibus dubitandum est"
  description = "Giovanni Martins is a software engineer with a passion for learning new things and sharing knowledge."
  socialShare = true

  [params.social]
    GitHub = "GiovanniSM20"
    Linkedin = "giovanni-martins"
    Email   = "giovannimartins2000@gmail.com"
    Gitlab = "giovannism20"
    Stackoverflow = "6398473/martins-giovanni"
    Goodreads = "48760650-giovanni"
    Strava = "11799379"

  [params.share]
    Twitter = true
    Facebook = true
    Linkedin = true
    Instagram = true

  [params.logo]
    url = "static/chicken.jpeg"
    width = 127
    height = 40

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1

  [languages.pt]
    lang = "pt"
    languageName = "Português"
    weight = 2
